# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
domain: asfoury.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://asfoury.github.io  # the base hostname and protocol for your site, e.g. http://example.com


title: ["Does Netflix have better quality movies than Amazon Prime?"]
description: [An exploration of the two streaming services to try and answer which one has better quality movies]


remote_theme: pages-themes/slate@v0.2.0

